name: Deploy project
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run lint
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: "Deploying project"
